# Generated by Django 2.2.4 on 2020-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
                ('monthlySales', models.IntegerField()),
                ('imageId', models.TextField()),
            ],
        ),
    ]
