# Generated by Django 2.2.4 on 2020-01-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPageModelMain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
                ('monthlySales', models.IntegerField()),
                ('imageId', models.TextField()),
                ('oilyScore', models.IntegerField()),
                ('dryScore', models.IntegerField()),
                ('sensitiveScore', models.IntegerField()),
            ],
            options={
                'db_table': 'item_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPageModelSub',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('imageId', models.TextField()),
                ('oilyScore', models.IntegerField()),
                ('dryScore', models.IntegerField()),
                ('sensitiveScore', models.IntegerField()),
            ],
            options={
                'db_table': 'item_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('oily', models.CharField(max_length=1)),
                ('dry', models.CharField(max_length=1)),
                ('sensitive', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageId', models.TextField()),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
                ('monthlySales', models.IntegerField()),
                ('oilyScore', models.IntegerField()),
                ('dryScore', models.IntegerField()),
                ('sensitiveScore', models.IntegerField()),
            ],
            options={
                'db_table': 'item_item',
            },
        ),
    ]
