# Generated by Django 2.2.4 on 2020-01-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('oily', models.CharField(max_length=1)),
                ('dry', models.CharField(max_length=1)),
                ('sensitive', models.CharField(max_length=1)),
            ],
        ),
    ]
